import "@/style/globals.css";

export const metadata = {
  title: "Entertainment web app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-darkBlue  ">{children}</body>
    </html>
  );
}
